steps:
  # 0) Python-step: installeer deps & draai main.py (die al naar availability/availability.json schrijft)
  - name: python:3.12-slim
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e

        echo "📦 Installing Python requirements"
        pip install --no-cache-dir -r requirements.txt

        echo "🚀 Running main.py"
        python main.py

        echo "✅ availability.json should now live in availability/"

  # 1) Firebase-deploy step: installeer firebase-tools & deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e

        echo "🛠️  Installing npm & Firebase CLI"
        apt-get update && apt-get install -y npm
        npm install -g firebase-tools

        echo "🔍 Workspace contents before deploy:"
        ls -R .

        echo "🚀 Deploying to Firebase Hosting (live channel)"
        firebase hosting:channel:deploy live \
          --project=gw-availability

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

serviceAccount: "projects/wash-exports/serviceAccounts/firebase-deployer@wash-exports.iam.gserviceaccount.com"